services:
  timeboardapp:
    build: .
    container_name: ${CONTAINER_NAME:-timeboardapp}
    environment:
      - TZ=${TZ:-UTC}
      - PGID=${PGID:-1000}
      - PUID=${PUID:-1000}
    networks:
      - net_internal
    ports:
      - "${PORT:-8888}:8888"
    restart: unless-stopped
    volumes:
      - ${CONFIG_DATA:-./data}:/data

networks:
  net_internal:
    external: true
    name: ${INTERNAL_NETWORK:-net_internal}
